// <auto-generated />
namespace Projeto2020.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Reserva : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reserva));
        
        string IMigrationMetadata.Id
        {
            get { return "202101071512337_Reserva"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
